apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: mockmarket-backend-config
  namespace: mockmarket
spec:
  healthCheck:
    checkIntervalSec: 15
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 2
    type: HTTP
    requestPath: /health
    port: 5001