# Build stage
FROM --platform=linux/amd64 node:18-alpine AS builder
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .

# Production stage
FROM --platform=linux/amd64 node:18-alpine
WORKDIR /usr/src/app
COPY --from=builder /usr/src/app/node_modules ./node_modules
COPY --from=builder /usr/src/app/package*.json ./
COPY --from=builder /usr/src/app/. .
COPY .env .env

ENV NODE_ENV=production \
    PORT=5001

EXPOSE 5001
CMD ["node", "src/app.js"]
