apiVersion: v1
kind: Secret
metadata:
  name: mockmarket-secrets
  namespace: mockmarket
type: Opaque
data:
  mongodb-uri: bW9uZ29kYitzcnY6Ly9tb2NrbWFya2V0MTIzOm1vY2ttYXJrZXQxMjNAbW9ja21hcmt0LWNsdXN0ZXIwLmFqNG9rLm1vbmdvZGIubmV0Lz9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHkmYXBwTmFtZT1tb2NrbWFya3QtY2x1c3RlcjA=
  jwt-secret: MGY5N2QxN2Q5NGMwMTRhZTM1ZGJjNGNhMTJhYTI4YTU3Y2Q0ODRlOTI3ZTAyZmVlY2NjMzMyOGE4MGJiYzhkYzRiZjU1YjczMmRlZWQxOTA1MWE0MzI2ZGIyNjBiNzJkN2VkZjQ0YWUxYThmMjcyZWM4YzBiMWQ2ZDQ0NGY0NzE=
  alpha-vantage-key: MDhaWlU2V01OSUdQTDhQVS4=